# vim: syntax=ruby

cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "autoconf"
brew "direnv"
brew "fish"
brew "fzf"
brew "readline"
brew "gawk"
brew "oniguruma"
brew "jq"
brew "neovim"
brew "nkf"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "tig"
brew "tmux"
brew "tree"

cask "alfred"
cask "deepl"
cask "google-chrome"
cask "intellij-idea-ce"
cask "iterm2"
cask "karabiner-elements"
cask "slack"
cask "visual-studio-code"
